### ISSUE TITLE
Error when extracting a certain lineage

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/covsonar#81]
Maybe it's because my installation of covsonar is not uptodate. If so, and this is not reproducible in the current code, please just close it. 

```bash
python3 sonar.py match --db gisaid.db --tsv --lineage BQ.1
```

Error:

```bash
Traceback (most recent call last):
  File "/scratch/hoelzerm/git/covsonar/sonar.py", line 529, in <module>
    snr.match_genomes(include_profiles=args.include, exclude_profiles=args.exclude, accessions=args.acc, lineages=args.lineage, with_sublineage=args.with_sublineage, zips=args.zip, dates=args.date, submission_dates=args.submission_date, labs=args.lab, sources=args.source, collections=args.collection, technologies=args.technology, platforms=args.platform, chemistries=args.chemistry, software=args.software, software_version=args.version, materials=args.material, min_ct=args.min_ct, max_ct=args.max_ct, ambig=args.ambig, count=args.count, frameshifts=frameshifts, tsv=args.tsv)
  File "/scratch/hoelzerm/git/covsonar/sonar.py", line 300, in match_genomes
    rows = self.db.match(include_profiles=include_profiles, exclude_profiles=exclude_profiles, accessions=accessions, lineages=lineages, with_sublineage=with_sublineage, zips=zips, dates=dates, submission_dates=submission_dates, labs=labs, sources=sources, collections=collections, technologies=technologies, chemistries=chemistries, software=software, software_version=software_version, materials=materials, min_ct=min_ct, max_ct=max_ct, ambig=ambig, count=count, frameshifts=frameshifts, debug=debug)
  File "/scratch/hoelzerm/git/covsonar/lib/sonardb.py", line 3012, in match
    rows[i]['dna_profile'] = self.filter_ambig(rows[i]['dna_profile'], self.iupac_explicit_nt_code, keep)
  File "/scratch/hoelzerm/git/covsonar/lib/sonardb.py", line 2623, in filter_ambig
    for mutation in list(filter(None, profile.split(" "))):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by hoelzer** [comment]
```bash
--lineage BQ% --with-sublineage
```

gives me the same error

**Comment by hoelzer** [comment]
python sonar.py --version
sonar.py 1.1.4

**Comment by hoelzer** [comment]
same problem with sonar.py 1.1.8

**Comment by hoelzer** [comment]
THe command works with the rki.db though

**Comment by hoelzer** [comment]
It works for Sofia in v1.1.7 though... weird...

**Comment by stephan-fuchs** [comment]
I am marking this issue as closed, as it appears to be an individual system problem. However, please do let me know if the issue persists or if you require any further assistance. Thank you for bringing this to our attention and for your cooperation in resolving the matter.
