### ISSUE TITLE
Error when extracting TSV from rki.db 2021-12-07

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/covsonar#82]
A weird error, maybe due to my covsonar installation. 

```bash
python3 /scratch/hoelzerm/git/covsonar/sonar.py match --db rki.db --date 2021-12-07:2021-12-07 --tsv > out.tsv
```

If it is not reproducible/ solved with a newer version, please feel free to close. 

I am using

```bash
sonar.py 1.1.8
```

**Comment by stephan-fuchs** [comment]
Hi Martin,

your notation includes an invalid date range. To filter based on a single date please use the following command:
`python3 /scratch/hoelzerm/git/covsonar/sonar.py match --db rki.db --date 2021-12-07 --tsv > out.tsv`

**Comment by hoelzer** [comment]
Hey, I get the same error:

```bash
python3 /scratch/hoelzerm/git/covsonar/sonar.py match --db rki.db --date 2021-12-07 --tsv > desh.tsv

Traceback (most recent call last):
  File "/scratch/hoelzerm/git/covsonar/sonar.py", line 530, in <module>
    snr.match_genomes(include_profiles=args.include, exclude_profiles=args.exclude, accessions=args.acc, lineages=args.lineage, with_sublineage=args.with_sublineage, zips=args.zip, dates=args.date, submission_dates=args.submission_date, labs=args.lab, sources=args.source, collections=args.collection, technologies=args.technology, platforms=args.platform, chemistries=args.chemistry, software=args.software, software_version=args.version, materials=args.material, min_ct=args.min_ct, max_ct=args.max_ct, ambig=args.ambig, count=args.count, frameshifts=frameshifts, tsv=args.tsv)
  File "/scratch/hoelzerm/git/covsonar/sonar.py", line 301, in match_genomes
    rows = self.db.match(include_profiles=include_profiles, exclude_profiles=exclude_profiles, accessions=accessions, lineages=lineages, with_sublineage=with_sublineage, zips=zips, dates=dates, submission_dates=submission_dates, labs=labs, sources=sources, collections=collections, technologies=technologies, platforms=platforms, chemistries=chemistries, software=software, software_version=software_version, materials=materials, min_ct=min_ct, max_ct=max_ct, ambig=ambig, count=count, frameshifts=frameshifts, debug=debug)
  File "/scratch/hoelzerm/git/covsonar/lib/sonardb.py", line 3069, in match
    rows[i]['dna_profile'] = self.filter_ambig(rows[i]['dna_profile'], self.iupac_explicit_nt_code, keep)
  File "/scratch/hoelzerm/git/covsonar/lib/sonardb.py", line 2646, in filter_ambig
    for mutation in list(filter(None, profile.split(" "))):
AttributeError: 'NoneType' object has no attribute 'split'
```

It does not happen when I use a date range before or after 2021-12-07 : ) 

Hach, edge case Martin on the road ;)

**Comment by stephan-fuchs** [comment]
Hello Martin,

I apologize for getting back to you so late. I wanted to follow up on the error you reported earlier. Could you please try out the version 1.1.7 of covSonar that can be setup by running the following commands:

git clone -b v1.1.7 https://github.com/rki-mf1/covsonar.git
cd covsonar
sonar.py --version

Please let me know if you are still encountering the same error. Thank you for your patience and cooperation in resolving this issue.

**Comment by ChaseWLW** [comment]
Hello @stephan-fuchs,

I ran into the same error message while running covsonar v1.1.8. The command is the follows:
```python sonar.py match --db $DB --cpus 36 --with-sublineage --lineage BA.% --tsv
```
$DB is gisaid_copy.db.

**Comment by matthuska** [comment]
I'm using the release version of covsonar 1.1.7 and get the same error, using a date range that doesn't include Martin's 2021-12-07:

Command:

```
$ sonar.py match --tsv --date 2021-02-01:2021-06-01 --db rki.db
```

Output
```
  File "<redacted>/src/covsonar-1.1.7/sonar.py", line 530, in <module>
    snr.match_genomes(include_profiles=args.include, exclude_profiles=args.exclude, accessions=args.acc, lineages=args.lineage, with_sublineage=args.with_sublineage, zips=args.zip, dates=args.date, submission_dates=args.submission_date, labs=args.lab, sources=args.source, collections=args.collection, technologies=args.technology, platforms=args.platform, chemistries=args.chemistry, software=args.software, software_version=args.version, materials=args.material, min_ct=args.min_ct, max_ct=args.max_ct, ambig=args.ambig, count=args.count, frameshifts=frameshifts, tsv=args.tsv)
  File "<redacted>/src/covsonar-1.1.7/sonar.py", line 301, in match_genomes
    rows = self.db.match(include_profiles=include_profiles, exclude_profiles=exclude_profiles, accessions=accessions, lineages=lineages, with_sublineage=with_sublineage, zips=zips, dates=dates, submission_dates=submission_dates, labs=labs, sources=sources, collections=collections, technologies=technologies, platforms=platforms, chemistries=chemistries, software=software, software_version=software_version, materials=materials, min_ct=min_ct, max_ct=max_ct, ambig=ambig, count=count, frameshifts=frameshifts, debug=debug)
  File "<redacted>/src/covsonar-1.1.7/lib/sonardb.py", line 3045, in match
    rows[i]['dna_profile'] = self.filter_ambig(rows[i]['dna_profile'], self.iupac_explicit_nt_code, keep)
  File "<redacted>/src/covsonar-1.1.7/lib/sonardb.py", line 2622, in filter_ambig
    for mutation in list(filter(None, profile.split(" "))):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ashkan98** [comment]
Hi all,

I get the same error for extracting a tsv for "BA.2" with:
`python3 covsonar/sonar.py match --lineage BA.2 --date 2021-12-02:2021-12-31 --db rki.db --tsv >BA2.tsv`

After shrinking the startdate down by brute-force I found out when the first sample was introduced (2021-12-10) in rki.db and could generate the tsv at `--date 2021-12-02:2021-12-31`
